[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "apps/frontend"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Přesměrování API volání (volitelné – když testuješ BE hostovaný jinde)
[[redirects]]
  from = "/api/*"
  to = "https://TVOJE-RENDER-API.onrender.com/:splat"
  status = 200
  force = true

# Security hlavičky (doporučeno)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
